### ISSUE TITLE
Where should putPoint and putJacobi be defined?

### ISSUE THREAD

**Issue by herumi** [herumi/ecdsa-motoko#11]
I made `putPoint` and `putJacobi` in `src/test_util.mo`. Those functions are useful for a debug.
But I try to import it from `src/curve.mo` to use `toHex` for a debug, it causes an error.
If I move those functions to `curve.mo`, then it must include `test_util.mo`, so I think it is easy that `toHex` is defined in `src/util.mo`.
How about it?

**Comment by timohanke** [comment]
I will:
* move `putPoint` and `putJacobi` directly into `curve.mo`
* put `toHex` into its own module `hex.mo` because it can probably be used in many different places

See [PR #12](https://github.com/herumi/ecdsa-motoko/pull/12)

**Comment by herumi** [comment]
Thank you for the refactoring.
